'use strict';

require('jquery');
require('jquery-ui');
require('file-download');
require('underscore');
require('angular');
require('angular-resource');
require('angular-sessionstorage');
require('bootstrap');
require('angular-ui-router');
require('angular-cookies');
require('moment');
require('angular-ui-bootstrap');
require('highcharts-ng');
require('highcharts');
require('highcharts/modules/exporting')(Highcharts);
require('highcharts/modules/offline-exporting')(Highcharts);
require('angular-input-masks');
require('angular-br-filters');
require('ngclipboard');
require('angular-permission');
require('angular-block-ui');
require('angular-sanitize');
require('ng-tags-input');
require('angular-timeago');
require('ng-file-upload');
require('angular-animate');
// require('ng-quill');
require('ng-toast');
require('textAngular-rangy');
require('textAngular-sanitize');
require('text-angular');
require('angular-filesize-filter');
require('angular-ui-mask');
require('angularjs-dropdown-multiselect');